//
//  Global-Bridging-Header.h
//  Candy
//
//  Created by liuyao on 15/7/1.
//  Copyright (c) 2015年 Sina. All rights reserved.
//

#ifndef Candy_Global_Bridging_Header_h
#define Candy_Global_Bridging_Header_h

#import "EaseMob.h"

#import "SlideMenuView.h"
//#import "AFNetworking.h"

//#define DEBUG           1
#define LYAppKey        "lucy61#candy"
#define LYClientID      "YXA6QSU8sB7tEeWC9NGVhz2ECA"
#define LYClientSecret  "YXA6itflnRWAi9VuKgT9oLOHrZY7fAM"

#define KNOTIFICATION_LOGINCHANGE @"loginStateChange"



///////////////////////////////////////
#import "EMCDDeviceManagerDelegate.h"
#import "EMCDDeviceManagerProximitySensorDelegate.h"
#import "DemoErrorCode.h"

#import "EMAudioPlayerUtil.h"
#import "EMAudioRecorderUtil.h"
#import "EMCDDeviceManager+Media.h"
#import "EMCDDeviceManager+Microphone.h"
#import "EMCDDeviceManager+ProximitySensor.h"
#import "EMCDDeviceManager+Remind.h"
#import "EMCDDeviceManager.h"
#import "EMCDDeviceManagerBase.h"
#import "EMAlertView.h"
#import "Emoji.h"
#import "EmojiEmoticons.h"
#import "macros.h"
#import "MBProgressHUD+Add.h"
#import "MBProgressHUD.h"
#import "MWCaptionView.h"
//#import "MWCommon.h"
#import "MWGridCell.h"
#import "MWGridViewController.h"
#import "MWPhoto.h"
#import "MWPhotoBrowser.h"
#import "MWPhotoBrowserPrivate.h"
#import "MWPhotoProtocol.h"
#import "MWTapDetectingImageView.h"
#import "MWTapDetectingView.h"
#import "MWZoomingScrollView.h"
#import "DACircularProgressView.h"
#import "EMSDImageCache.h"
#import "EMSDWebImageCompat.h"
#import "EMSDWebImageDecoder.h"
#import "EMSDWebImageDownloader.h"
#import "EMSDWebImageDownloaderOperation.h"
#import "EMSDWebImageManager.h"
#import "EMSDWebImageOperation.h"
#import "EMSDWebImagePrefetcher.h"
#import "MKAnnotationView+EMWebCache.h"
#import "NSData+EMImageContentType.h"
#import "UIButton+EMWebCache.h"
#import "UIImage+EMGIF.h"
#import "UIImage+EMMultiFormat.h"
#import "UIImage+EMWebP.h"
#import "UIImageView+EMHighlightedWebCache.h"
#import "UIImageView+EMWebCache.h"
#import "UIView+EMWebCacheOperation.h"
#import "NSIndexPath+PSTCollectionViewAdditions.h"
#import "PSTCollectionView.h"
#import "PSTCollectionViewCell.h"
#import "PSTCollectionViewCommon.h"
#import "PSTCollectionViewController.h"
#import "PSTCollectionViewData.h"
#import "PSTCollectionViewFlowLayout.h"
#import "PSTCollectionViewItemKey.h"
#import "PSTCollectionViewLayout+Internals.h"
#import "PSTCollectionViewLayout.h"
#import "PSTCollectionViewUpdateItem.h"
#import "PSTGridLayoutInfo.h"
#import "PSTGridLayoutItem.h"
#import "PSTGridLayoutRow.h"
#import "PSTGridLayoutSection.h"
#import "SRDefine.h"
#import "SRRefreshView.h"
#import "SRSlimeView.h"
#import "THProgressView.h"
#import "TTGlobalUICommon.h"
#import "MobClick.h"
//#import "amrFileCodec.h"
//#import "wav.h"
//#import "EMVoiceConverter.h"
//#import "interf_dec.h"
//#import "interf_enc.h"
//#import "dec_if.h"
//#import "if_rom.h"
#import "NSDate+Category.h"
#import "NSDateFormatter+Category.h"
#import "NSString+Valid.h"
#import "UIResponder+Router.h"
#import "UIViewController+DismissKeyboard.h"
#import "UIViewController+HUD.h"
#import "ChatDemoUIDefine.h"
#import "CallViewController.h"
#import "ChatListCell.h"
#import "ChatListViewController.h"
#import "ChatSendHelper.h"
#import "ChatViewController+Category.h"
#import "ChatViewController.h"
#import "ConvertToCommonEmoticonsHelper.h"
#import "LocationViewController.h"
#import "DXMessageToolBar.h"
#import "DXFaceView.h"
#import "FacialView.h"
#import "DXChatBarMoreView.h"
#import "DXRecordView.h"
#import "EMChatAudioBubbleView.h"
#import "EMChatBaseBubbleView.h"
#import "EMChatImageBubbleView.h"
#import "EMChatLocationBubbleView.h"
#import "EMChatTextBubbleView.h"
#import "EMChatVideoBubbleView.h"
#import "EMChatTimeCell.h"
#import "EMChatViewBaseCell.h"
#import "EMChatViewCell.h"
#import "MessageModel.h"
#import "MessageModelManager.h"
#import "MessageReadManager.h"
#import "ChatGroupDetailViewController.h"
#import "ContactSelectionViewController.h"
#import "ContactView.h"
#import "CreateGroupViewController.h"
#import "GroupBansViewController.h"
#import "GroupListViewController.h"
#import "GroupSettingViewController.h"
#import "GroupSubjectChangingViewController.h"
#import "PublicGroupDetailViewController.h"
#import "PublicGroupListViewController.h"
#import "ChatroomDetailViewController.h"
#import "ChatroomListViewController.h"
#import "MyChatroomListViewController.h"
#import "ChineseToPinyin.h"
#import "ContactsViewController.h"
#import "AddFriendCell.h"
#import "AddFriendViewController.h"
#import "ApplyFriendCell.h"
#import "ApplyViewController.h"
#import "RealtimeSearchUtil.h"
#import "InvitationManager.h"
#import "LoginViewController.h"
#import "MainViewController.h"
#import "BackupViewController.h"
#import "BlackListViewController.h"
#import "DebugViewController.h"
#import "EditNicknameViewController.h"
#import "PushNotificationViewController.h"
#import "SettingsViewController.h"
#import "BaseTableViewCell.h"
#import "EMSearchBar.h"
#import "EMTextView.h"
#import "EMRemarkImageView.h"
#import "BaseViewController.h"
#import "EMChooseViewController.h"
#import "EMNavigationController.h"
#import "EMSearchDisplayController.h"
#import "XHMessageTextView.h"

#endif
